package shirei

import (
	"slices"
	"strings"
	"unicode"

	"golang.org/x/text/unicode/bidi"

	g "go.hasen.dev/generic"

	"github.com/cespare/xxhash/v2"
	"github.com/go-text/typesetting/harfbuzz"
	"github.com/go-text/typesetting/language"

	"github.com/dboslee/lru"
)

type TextStyle struct {
	Families []string
	FontAspect

	Color Vec4
	Size  f32
}

type TextAttrSet struct {
	TextStyle

	MaxWidth f32
}

func DefaultFontAspect() FontAspect {
	return FontAspect{
		Weight:  WeightNormal,
		Style:   StyleNormal,
		Stretch: StretchNormal,
	}
}

const DefaultTextSize = 12

func DefaultTextStyle() TextStyle {
	return TextStyle{
		Color:      Vec4{0, 0, 0, 1},
		Size:       DefaultTextSize,
		FontAspect: DefaultFontAspect(),
	}
}

func DefaultTextAttrs() TextAttrSet {
	return TextAttrSet{
		TextStyle: DefaultTextStyle(),
	}
}

// the background color of selected text
var SelectionColor = Vec4{220, 50, 70, 0.5}

// the smallest rune index on the line, or -1 if the line has no glyphs
func lineFirstCluster(line *ShapedTextLine) int {
	first := -1
	for _, s := range line.Segments {
		for _, g := range s.Glyphs {
			if first < 0 || int(g.Cluster) < first {
				first = int(g.Cluster)
			}
		}
	}
	return first
}

func ShapedTextLineLayout(line *ShapedTextLine, attrs TextAttrSet, baseDir Direction, selectionFrom int, selectionTo int, nextLinePaddingTop *f32) {
	// the line box is attrs.Size (the em box) tall; the rest of the line
	// height (the leading) is applied as top padding, spacing this line from
	// the previous one
	leading := *nextLinePaddingTop

	// expand-across is necessary for the alignment to work
	var lineAttrs AttrSet
	lineAttrs.Row = true
	lineAttrs.NoAnimate = true
	lineAttrs.ExpandAcross = true
	lineAttrs.MaxSize[0] = attrs.MaxWidth
	lineAttrs.MinSize[1] = attrs.Size
	lineAttrs.Padding[PAD_TOP] = leading
	*nextLinePaddingTop = line.Height - attrs.Size

	// TODO: allow text attribute to control alignment
	if baseDir == RTL {
		lineAttrs.MainAlign = AlignEnd
	}

	// selection highlight geometry: floats anchor at the container origin,
	// above the top padding, so the em box sits at y=leading. When the
	// selection comes in from an earlier line, the highlight grows upward to
	// also cover the leading, so consecutive selected lines form one
	// continuous block.
	bgOrigin := Vec2{0, leading}
	bgHeight := attrs.Size
	first := lineFirstCluster(line)
	if leading > 0 && first >= 0 && selectionFrom < first {
		bgOrigin[1] = 0
		bgHeight += leading
	}

	Container(lineAttrs, func() {
		// pass 1: background highlight
		Container(AttrSet{Floats: true, Float: bgOrigin, Row: true, ExpandAcross: true}, func() {
			if selectionFrom != selectionTo {
				for _, s := range line.Segments {
					for _, g := range s.Glyphs {
						var bg AttrSet
						bg.MinSize[0] = g.XAdvance // FIXME: use width instead of x advance?
						bg.MinSize[1] = bgHeight
						runeIndex := int(g.Cluster)
						if runeIndex >= selectionFrom && runeIndex < selectionTo {
							bg.Background = SelectionColor
						}
						Element(bg)
					}
				}
			}
		})

		// pass 2: actual glyphs
		for _, s := range line.Segments {
			for _, g := range s.Glyphs {
				var a AttrSet
				a.MinSize[0] = g.XAdvance
				a.MinSize[1] = attrs.Size
				a.Background = attrs.Color

				Container(a, func() {
					current.fontId = g.FontId
					current.glyphId = g.GlyphId
					current.glyphOffset = g.Offset
				})
			}
		}
	})
}

func ShapedTextLayout(shaped ShapedText, attrs TextAttrSet, selectionFrom int, selectionTo int) {
	var blockAttrs AttrSet
	blockAttrs.MaxSize[0] = attrs.MaxWidth
	// TODO: allow text attribute to control alignment
	if shaped.BaseDir == RTL {
		blockAttrs.SelfAlign = AlignEnd
	}

	var nextLinePaddingTop float32 // to manage spaces between lines

	Container(blockAttrs, func() {
		for idx := range shaped.Lines {
			line := &shaped.Lines[idx]
			ShapedTextLineLayout(line, attrs, shaped.BaseDir, selectionFrom, selectionTo, &nextLinePaddingTop)
		}
	})
}

// Generated by ChatGPT (initially)
func SafeTruncateUTF8(s string, limit int) string {
	if len(s) <= limit {
		return s
	}
	cut := limit
	backstop := max(0, limit-4)

	// step back while in continuation bytes (10xxxxxx)
	for cut > backstop && (s[cut]&0xC0) == 0x80 {
		cut--
	}
	return s[:cut]
}

// Text renders a run of text with the given text attributes as a leaf of the
// current container. Label is the usual convenience wrapper over it.
func Text(label string, attrs TextAttrSet) {
	// For performance reasons, do not accept text larger than 16kb
	// We will add a segmented text view in the future to handle large text blobs
	label = SafeTruncateUTF8(label, 16*1024)

	shaped := ShapeText(label, attrs)
	ShapedTextLayout(shaped, attrs, 0, 0)
}

type TextLayout struct {
	Segments []GlyphsSegment
}

type GlyphsSegment struct {
	GlyphSegmentProps
	Width           float32
	Height          float32
	EndsWithNewline bool
	Glyphs          []Glyph
}

type Glyph struct {
	FontId   FontId
	GlyphId  GlyphId
	Cluster  int32
	Offset   Vec2
	XAdvance float32
	Width    float32
	// Scale float32

	// FIXME should this be here?
	Direction Direction
}

var hbfonts = make(map[FontId]*harfbuzz.Font)

func shapeSegment(props GlyphSegmentProps, text []rune, start, length int) (s GlyphsSegment) {
	s.GlyphSegmentProps = props
	s.EndsWithNewline = length > 0 && text[start+length-1] == '\n'
	s.Glyphs = make([]Glyph, 0, length)

	fontId := props.font

	if fontId == 0 {
		// FIXME should we fill in some values??
		return s
	}

	face := GetFace(fontId)

	buf := harfbuzz.NewBuffer()

	buf.AddRunes(text, start, length)
	buf.Props.Script = props.sc
	buf.Props.Direction = harfbuzz.LeftToRight + harfbuzz.Direction(props.Dir)
	buf.Props.Language = "en-EN"

	// this could set language to utf-8 which would *crash* the language parser!!
	// buf.GuessSegmentProperties() // this seems to just set the default locale language; regardless of content!

	font := hbfonts[fontId]
	if font == nil {
		ttf := GetParsedFont(fontId)
		if ttf == nil {
			return s
		}
		font = harfbuzz.NewFont(ttf)
		hbfonts[fontId] = font
		// TODO use lru cache instead of map?
	}

	buf.Shape(font, nil)

	scaleFactor := face.InvUPM * props.size

	s.Height = scaleFactor * (face.Ascender - face.Descender)

	for i := range buf.Info {
		inf := buf.Info[i]
		pos := buf.Pos[i]
		r := text[inf.Cluster]

		xAdvance := float32(pos.XAdvance) * scaleFactor
		width := max(xAdvance, GlyphWidth(fontId, inf.Glyph)*scaleFactor)

		// special support for tabs!
		if r == '\t' {
			stdg := LookupGlyph(fontId, 'M')
			width = GlyphWidth(fontId, stdg) * 4
			width *= scaleFactor
			xAdvance = width
		}
		// Newlines force line breaks at the segment layer; they should
		// still occupy an index for editing, but they must not render as
		// the phantom advance that indents the following hard line.
		if r == '\n' {
			width = 0
			xAdvance = 0
		}

		g.Append(&s.Glyphs, Glyph{
			FontId:    fontId,
			GlyphId:   inf.Glyph,
			Cluster:   int32(inf.Cluster),
			Offset:    Vec2{float32(pos.XOffset) * scaleFactor, float32(pos.YOffset) * scaleFactor},
			XAdvance:  xAdvance,
			Width:     width,
			Direction: props.Dir,
		})
		// width is accumulated xadvances
		// only the last item we should take the max of width and xadvance but
		// for now we don't bother. we'll look into this if it proves to be a
		// real problem
		s.Width += xAdvance
	}

	return s
}

func produceShapedSegments(runes []rune, dirs []Direction, fontIds []FontId, aspect FontAspect, size float32) []GlyphsSegment {
	var allSegments = make([]GlyphsSegment, 0, len(runes)/2)

	var lineNo int

	getSegmentProps := func(i int) GlyphSegmentProps {
		ch := runes[i]
		font, _ := findMatchingFontAndGlyph(ch, fontIds, aspect)
		return GlyphSegmentProps{
			font:    font,
			size:    size,
			sc:      language.LookupScript(ch),
			Dir:     dirs[i],
			isSpace: isSpace(ch),
			lineNo:  lineNo,
		}
	}

	var segment = getSegmentProps(0)
	if runes[0] == '\n' {
		lineNo++
	}
	var start = 0
	for i := 1; i < len(runes); i++ {
		segmentNext := getSegmentProps(i)
		if runes[i] == '\n' {
			lineNo++
		}

		// special case!!
		if segmentNext.sc == language.Inherited {
			segmentNext.sc = segment.sc
		}

		if segmentNext != segment {
			length := i - start
			allSegments = append(allSegments, shapeSegment(segment, runes, start, length))
			segment = segmentNext
			start = i
		}
	}
	// last segment!
	length := len(runes) - start
	allSegments = append(allSegments, shapeSegment(segment, runes, start, length))

	// log.Println("Segmentation Duration:", segdur)
	// log.Println("    Font Lookup Duration:", lookupdur)
	// log.Println("Shaping Duration:", shapedur)
	// log.Println("    HarfBuzz Duration:", hbdur)
	return allSegments
}

func lineBreakShapedSegments(allSegments []GlyphsSegment, attrs TextAttrSet) []ShapedTextLine {

	// break segments into lines
	var lines []ShapedTextLine
	{
		var prevLineNo int // first segment always has line number set to 0
		var maxWidth = attrs.MaxWidth
		var widthAcc float32
		var height float32
		var start int
		for i, segment := range allSegments {
			var widthOverflow = i > start && maxWidth > 0 && segment.Width+widthAcc > maxWidth
			var forceLineBreak = segment.lineNo > prevLineNo
			if widthOverflow || forceLineBreak {
				lines = append(lines, ShapedTextLine{
					Segments: allSegments[start:i],
					Width:    widthAcc,
					Height:   height,
				})
				start = i
				widthAcc = 0
				height = 0
			}
			widthAcc += segment.Width
			height = max(height, segment.Height)
			prevLineNo = segment.lineNo
		}
		lines = append(lines, ShapedTextLine{
			Segments: allSegments[start:],
			Width:    widthAcc,
			Height:   height,
		})
		if allSegments[len(allSegments)-1].EndsWithNewline {
			if height == 0 {
				height = attrs.Size
			}
			lines = append(lines, ShapedTextLine{
				Height: height,
			})
		}
	}

	var baseDir = allSegments[0].Dir
	var reverseDir = baseDir ^ 1 // flips the lower bit, and we only have two values, so

	// reverse continuous reverse runs
	for i := range lines {
		line := &lines[i]

		// if RTL, flip the entire thing first, then flip LTR runs
		// if LTR, just flip RTL runs
		if baseDir == RTL {
			slices.Reverse(line.Segments)
		}

		var dir = baseDir
		var start = 0
		for i := range line.Segments {
			dir1 := line.Segments[i].Dir
			if dir == baseDir && dir1 == reverseDir {
				// start of a new reverse run
				start = i
				dir = dir1
			} else if dir == reverseDir && dir1 == baseDir {
				// end of revers run
				slices.Reverse(line.Segments[start:i])
				start = -1
				dir = dir1
			}
		}
		// last reverse run!
		if dir == reverseDir {
			slices.Reverse(line.Segments[start:])
		}
	}

	return lines
}

type Direction byte

const (
	LTR Direction = iota
	RTL
)

type GlyphSegmentProps struct {
	font    FontId
	size    float32
	sc      language.Script
	Dir     Direction
	isSpace bool
	lineNo  int // hack for line breaks
}

func isSpace(ch rune) bool {
	return unicode.Is(unicode.Zs, ch)
}

type ShapedText struct {
	Runes   []rune
	BaseDir Direction
	Lines   []ShapedTextLine
}

type ShapedTextLine struct {
	Segments []GlyphsSegment
	Width    float32
	Height   float32
}

// shapeCache: capacity must comfortably exceed the number of distinct
// visible strings in a busy frame, or the LRU thrashes (every entry
// evicted before its next use — the whole UI re-shaped through harfbuzz
// every frame). A profiler table view alone can show 250+ strings; 4096
// entries of label-sized ShapedText is a few MB, cheap next to what
// shaping costs. Effectiveness is pinned by see_pprof's
// TestShapeCacheSteadyState.
var shapeCache = lru.New[uint64, ShapedText](lru.WithCapacity(4096))

// ShapeStats counts ShapeText invocations vs cache hits — the diagnostic
// for shape-cache effectiveness. In steady state (no text changing between
// frames) hits should track calls; a persistent gap means the UI is paying
// harfbuzz every frame. Pinned by see_pprof's TestShapeCacheSteadyState.
var ShapeStats struct {
	Calls int64
	Hits  int64
}

func ShapeText(text string, attrs TextAttrSet) ShapedText {
	fontIds := make([]FontId, 0, len(attrs.Families))
	for _, fontName := range attrs.Families {
		fontIds = append(fontIds, LookupFace(FaceLookupKey{fontName, attrs.FontAspect}))
	}

	var shaped ShapedText
	if len(text) == 0 {
		return ShapedText{}
	}
	ShapeStats.Calls++

	// Caching. The key hashes the string CONTENTS — not the header: a
	// header (pointer) key means every fmt.Sprintf-built label is a fresh
	// key each frame, so dynamic strings never hit AND their garbage
	// entries evict the stable ones (see_pprof showed harfbuzz burning 33%
	// of cumulative time on a fully static screen). Hashing the bytes costs
	// nanoseconds; shaping costs microseconds. Color is deliberately NOT in
	// the key: it isn't baked into ShapedText (it's applied at layout time),
	// so keying on it only fragments the cache.
	var cacheKey uint64
	{
		var hash = xxhash.New()
		hash.WriteString(text)
		Hash(hash, &attrs.MaxWidth)
		Hash(hash, &attrs.Size)
		Hash(hash, &attrs.FontAspect)
		HashSlice(hash, fontIds)
		cacheKey = hash.Sum64()

		cached, cacheFound := shapeCache.Get(cacheKey)
		if cacheFound {
			ShapeStats.Hits++
			return cached
		}
	}

	var runes = []rune(text)
	var dirs = ParagraphBidi(text)
	allSegments := produceShapedSegments(runes, dirs, fontIds, attrs.FontAspect, attrs.Size)
	shaped.Runes = runes
	shaped.BaseDir = allSegments[0].Dir
	shaped.Lines = lineBreakShapedSegments(allSegments, attrs)

	shapeCache.Set(cacheKey, shaped)

	return shaped
}

func findMatchingFontAndGlyph(ch rune, fonts []FontId, aspect FontAspect) (FontId, GlyphId) {
	var fontId FontId
	var glyphId GlyphId
	for _, fid := range fonts {
		gid := LookupGlyph(fid, ch)
		if gid == 0 {
			continue
		} else {
			fontId = fid
			glyphId = gid
			break
		}
	}

	if fontId == 0 || glyphId == 0 {
		return FallbackFontFor(ch, aspect)
	}

	return fontId, glyphId
}

var bidiCache = lru.New[string, []Direction]()

// works with a single line of text, not an article with multiple paragraphs!
func ParagraphBidi(txt string) []Direction {
	out, found := bidiCache.Get(txt)
	if found {
		return out
	}

	out = make([]Direction, 0, len(txt))

	for line := range strings.SplitSeq(txt, "\n") {
		var paragraph bidi.Paragraph
		paragraph.SetString(line)
		ordering, err := paragraph.Order()
		if err != nil {
			panic(err)
		}
		for i := range ordering.NumRuns() {
			run := ordering.Run(i)
			start, end := run.Pos() // NOTE: end is inclusive
			dir := Direction(run.Direction())
			for j := start; j <= end; j++ {
				out = append(out, dir)
			}
		}
		out = append(out, LTR) // FIXME the dir for the newline character ..
	}

	bidiCache.Set(txt, out)

	return out
}
