//go:build ignore

// Generates icons_gen.go: a NamedIcon entry for every Sym* (Microns) and
// Typ* (Typicons) IconGlyph var in the widgets package, in source order —
// the files group related icons together, which reads better in the gallery
// than alphabetical would. The emitted table references the vars by name,
// so a rename or removal in widgets breaks this example's build instead of
// silently drifting.
//
// Run from this directory (go generate does): go run gen.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen.go; DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import . \"go.hasen.dev/shirei/widgets\"\n\n")
	buf.WriteString("var allIcons = []*NamedIcon{\n")
	for _, src := range []struct{ path, prefix string }{
		{"../../widgets/microns.go", "Sym"},
		{"../../widgets/typicons.go", "Typ"},
	} {
		for _, name := range varNames(src.path, src.prefix) {
			fmt.Fprintf(&buf, "\t{%q, %s},\n", name, name)
		}
	}
	buf.WriteString("}\n")
	if err := os.WriteFile("icons_gen.go", buf.Bytes(), 0644); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func varNames(path, prefix string) []string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	var out []string
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, spec := range gd.Specs {
			for _, ident := range spec.(*ast.ValueSpec).Names {
				if strings.HasPrefix(ident.Name, prefix) {
					out = append(out, ident.Name)
				}
			}
		}
	}
	return out
}
