package widgets

import (
	_ "embed"
	"log"

	. "go.hasen.dev/shirei"
	. "go.hasen.dev/shirei/tw"
)

// Acknowledgement:
// Microns icon font is designed by Stephen Hutchings
// Distributed under the terms of SIL Open Font License (OFL) version 1.1

//go:embed microns.ttf
var micronBytes []byte

func UseMicronFont() {
	err := UseFontBytes(micronBytes)
	if err != nil {
		log.Println(err)
	}
}

func Icon(sym rune, fns ...TextAttrsFn) {
	fns = append(fns, Fonts("Microns", "Typicons")) // fortunately, microns and typicons rune ranges do not overlap!
	Label(string(sym), fns...)
}

const SymArrowLeft = '\uE700'
const SymArrowRight = '\uE701'
const SymArrowUp = '\uE702'
const SymArrowDown = '\uE703'
const SymLeft = '\uE704'
const SymRight = '\uE705'
const SymUp = '\uE706'
const SymDown = '\uE707'
const SymUpload = '\uE708'
const SymDownload = '\uE709'
const SymUndo = '\uE70A'
const SymRedo = '\uE70B'
const SymReplay = '\uE70C'
const SymRefresh = '\uE796'
const SymExternal = '\uE773'
const SymInternal = '\uE795'
const SymPlus = '\uE70D'
const SymMinus = '\uE70E'
const SymCaret = '\uE70F'
const SymCaretUp = '\uE710'
const SymCaretDown = '\uE711'
const SymILeft = '\uE712'
const SymIRight = '\uE713'
const SymIUp = '\uE714'
const SymIDown = '\uE715'
const SymITick = '\uE718'
const SymICross = '\uE719'
const SymIPlus = '\uE716'
const SymIMinus = '\uE717'
const SymIEqual = '\uE7A6'
const SymIDivide = '\uE7A7'
const SymIBullet = '\uE71A'
const SymIAsterisk = '\uE71B'
const SymPlay = '\uE71C'
const SymPause = '\uE71D'
const SymPrev = '\uE774'
const SymNext = '\uE775'
const SymSubtitles = '\uE71E'
const SymVolLow = '\uE71F'
const SymVolMid = '\uE720'
const SymVolHigh = '\uE721'
const SymVolMute = '\uE722'
const SymCaptions = '\uE723'
const SymHd = '\uE724'
const SymAudioDescription = '\uE725'
const SymChartLine = '\uE726'
const SymChartBar = '\uE727'
const SymChartScatter = '\uE728'
const SymChartArea = '\uE7A3'
const SymChartPie = '\uE729'
const SymCalendar = '\uE72A'
const SymClock = '\uE72B'
const SymStar = '\uE72C'
const SymHeart = '\uE72D'
const SymFlag = '\uE72E'
const SymBookmark = '\uE72F'
const SymChat = '\uE730'
const SymEdit = '\uE731'
const SymDelete = '\uE732'
const SymShow = '\uE733'
const SymHide = '\uE734'
const SymLock = '\uE735'
const SymBan = '\uE7A4'
const SymPipette = '\uE7A5'
const SymLink = '\uE737'
const SymAttach = '\uE776'
const SymUser = '\uE738'
const SymGroup = '\uE739'
const SymFile = '\uE73A'
const SymFolder = '\uE777'
const SymImage = '\uE73B'
const SymVideo = '\uE73C'
const SymAudio = '\uE73D'
const SymMicrophone = '\uE778'
const SymVideoCamera = '\uE779'
const SymPrint = '\uE73E'
const SymMenu = '\uE73F'
const SymBars = '\uE740'
const SymHome = '\uE77A'
const SymCancel = '\uE741'
const SymCog = '\uE736'
const SymOptsH = '\uE742'
const SymOptsV = '\uE743'
const SymSearch = '\uE744'
const SymZoomIn = '\uE745'
const SymZoomOut = '\uE746'
const SymContract = '\uE747'
const SymExpand = '\uE748'
const SymGrid = '\uE749'
const SymMatrix = '\uE74A'
const SymList = '\uE77B'
const SymRss = '\uE74C'
const SymShare = '\uE74D'
const SymMail = '\uE74E'
const SymCode = '\uE74F'
const SymBox = '\uE750'
const SymBoxFull = '\uE751'
const SymBoxPlus = '\uE752'
const SymBoxMinus = '\uE753'
const SymBoxTick = '\uE754'
const SymBoxCross = '\uE755'
const SymBoxPlusO = '\uE77D'
const SymBoxMinusO = '\uE77C'
const SymBoxTickO = '\uE77E'
const SymBoxCrossO = '\uE77F'
const SymRadioOff = '\uE756'
const SymRadioOn = '\uE757'
const SymRadioFull = '\uE758'
const SymInfo = '\uE759'
const SymWarn = '\uE75A'
const SymPass = '\uE75B'
const SymFail = '\uE75C'
const SymUnknown = '\uE780'
const SymText = '\uE75D'
const SymBold = '\uE75E'
const SymItalic = '\uE75F'
const SymUnderline = '\uE760'
const SymStrikeout = '\uE761'
const SymTextSize = '\uE762'
const SymTextUnstyle = '\uE763'
const SymTranslate = '\uE786'
const SymAlignLeft = '\uE764'
const SymAlignCenter = '\uE765'
const SymAlignRight = '\uE766'
const SymJustifyLeft = '\uE782'
const SymJustifyCenter = '\uE781'
const SymJustifyRight = '\uE783'
const SymIndent = '\uE767'
const SymOutdent = '\uE768'
const SymSortAsc = '\uE784'
const SymSortDesc = '\uE785'
const SymChapters = '\uE74B'
const SymColumns = '\uE7A2'
const SymCloud = '\uE769'
const SymWeb = '\uE76A'
const SymWifi = '\uE76B'
const SymDrive = '\uE787'
const SymServer = '\uE788'
const SymPower = '\uE789'
const SymCopy = '\uE78A'
const SymLandscape = '\uE78D'
const SymPortrait = '\uE78E'
const SymPanelLeft = '\uE78F'
const SymPanelRight = '\uE790'
const SymMin = '\uE791'
const SymMax = '\uE792'
const SymScale = '\uE793'
const SymScaleH = '\uE79B'
const SymScaleV = '\uE79C'
const SymMove = '\uE794'
const SymMoveAlt = '\uE79D'
const SymSwap = '\uE79E'
const SymShuffle = '\uE79F'
const SymAbove = '\uE78B'
const SymBelow = '\uE78C'
const SymDifference = '\uE797'
const SymIntersect = '\uE798'
const SymOutline = '\uE799'
const SymUnite = '\uE79A'
const SymParagraph = '\u00B6'
const SymSub = '\uE7A0'
const SymSup = '\uE7A1'
const SymAt = '\u0040'
const SymHash = '\u0023'
