package main

import (
	"archive/zip"
	"bufio"
	"fmt"
	_ "golang.org/x/image/webp"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	"image/png"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"golang.org/x/image/draw"
)

const (
	minSdk    = 21
	targetSdk = 30
	libName   = "shireiapp" // manifest android.app.lib_name; file lib<name>.so
	// xxxhdpi launcher icon edge length (px).
	launcherIconSize = 192
)

// AndroidOpts is one Android build+run request — filled from CLI flags or the GUI.
type AndroidOpts struct {
	PkgDir    string // absolute directory of a package main
	Arch      string // "arm64" or "arm"
	AppID     string // application id; empty → {IDPrefix}.<name>
	Label     string // launcher label; default folder name
	IconPath  string // optional launcher icon image
	IDPrefix  string // reverse-DNS stem when AppID empty; default dev.shirei
	Serial    string // adb device serial; empty = the only/default device
	BuildOnly bool
	Screencap string // save a post-launch screenshot here
	DelayMs   int    // wait before the screenshot
}

type logFn func(format string, args ...any)

// buildAndRun executes the full pipeline: export file → c-shared build with
// the NDK clang → aapt2 link → lib injection → zipalign → apksigner →
// adb install → am start (→ optional screencap).
func buildAndRun(o AndroidOpts, logf logFn) error {
	if st, err := os.Stat(o.PkgDir); err != nil || !st.IsDir() {
		return fmt.Errorf("package dir not found: %s", o.PkgDir)
	}

	sdk, err := findSDK()
	if err != nil {
		return err
	}
	ndk, err := newestSubdir(filepath.Join(sdk, "ndk"))
	if err != nil {
		return fmt.Errorf("NDK not found under %s/ndk — sdkmanager --install 'ndk;...': %w", sdk, err)
	}
	buildTools, err := newestSubdir(filepath.Join(sdk, "build-tools"))
	if err != nil {
		return fmt.Errorf("build-tools not found — sdkmanager --install 'build-tools;...': %w", err)
	}
	platform, err := newestSubdir(filepath.Join(sdk, "platforms"))
	if err != nil {
		return fmt.Errorf("platforms not found — sdkmanager --install 'platforms;android-...': %w", err)
	}
	androidJar := filepath.Join(platform, "android.jar")

	var goarch, cc, abi string
	ccDir := filepath.Join(ndk, "toolchains/llvm/prebuilt", ndkHostTag(), "bin")
	switch o.Arch {
	case "", "arm64":
		goarch, abi = "arm64", "arm64-v8a"
		cc = filepath.Join(ccDir, fmt.Sprintf("aarch64-linux-android%d-clang", minSdk))
	case "arm":
		goarch, abi = "arm", "armeabi-v7a"
		cc = filepath.Join(ccDir, fmt.Sprintf("armv7a-linux-androideabi%d-clang", minSdk))
	default:
		return fmt.Errorf("unsupported arch %q (arm64 or arm)", o.Arch)
	}
	if runtime.GOOS == "windows" {
		cc += ".cmd" // the per-API clang wrappers are batch scripts on Windows
	}
	if err := checkNDKHostToolchain(ndk, cc); err != nil {
		return err
	}

	moduleRoot := findUp(o.PkgDir, "go.mod")
	if moduleRoot == "" {
		return fmt.Errorf("no go.mod above %s", o.PkgDir)
	}
	binRoot := moduleRoot
	if w := findUp(o.PkgDir, "go.work"); w != "" {
		binRoot = w
	}

	folderBase := filepath.Base(o.PkgDir)
	appName := sanitizeName(folderBase) // filesystem-safe build dir name
	appID := androidPackageName(o.AppID, o.IDPrefix, folderBase)
	label := o.Label
	if label == "" {
		label = folderBase
	}
	logf("— application id %s", appID)
	buildDir := filepath.Join(binRoot, "bin", "android", appName)
	if err := os.MkdirAll(buildDir, 0o755); err != nil {
		return err
	}

	// --- 1. temporary export file so the .so can call the package's main() ---
	exportFile := filepath.Join(o.PkgDir, "zz_shirei_android_export.go")
	exportSrc := `//go:build android

// Code generated by mobilerun — do not commit.
// Called by androidbackend's android_main after the glue starts the app thread.
package main

import "C"

//export shirei_android_main
func shirei_android_main() {
	main()
}
`
	if err := os.WriteFile(exportFile, []byte(exportSrc), 0o644); err != nil {
		return err
	}
	defer os.Remove(exportFile)

	// --- 2. go build -buildmode=c-shared with the NDK clang ---
	rel, err := filepath.Rel(moduleRoot, o.PkgDir)
	if err != nil {
		return err
	}
	soPath := filepath.Join(buildDir, "lib", abi, "lib"+libName+".so")
	if err := os.MkdirAll(filepath.Dir(soPath), 0o755); err != nil {
		return err
	}
	logf("— go build c-shared GOOS=android GOARCH=%s (./%s)", goarch, rel)
	cmd := exec.Command("go", "build", "-buildmode=c-shared", "-o", soPath, "./"+rel)
	cmd.Dir = moduleRoot
	cmd.Env = append(os.Environ(),
		"CGO_ENABLED=1", "GOOS=android", "GOARCH="+goarch, "CC="+cc)
	if goarch == "arm" {
		cmd.Env = append(cmd.Env, "GOARM=7")
	}
	if err := runCmd(logf, cmd); err != nil {
		return fmt.Errorf("go build: %w", err)
	}
	os.Remove(strings.TrimSuffix(soPath, ".so") + ".h") // header is unused

	// --- 3. compile the Java host activity (keyboard/IME) → classes.dex ---
	javaBytes, err := shireiActivityJavaBytes()
	if err != nil {
		return fmt.Errorf("embedded ShireiActivity.java: %w", err)
	}
	javaSrc := filepath.Join(buildDir, "java", "dev", "shirei", "host", "ShireiActivity.java")
	if err := os.MkdirAll(filepath.Dir(javaSrc), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(javaSrc, javaBytes, 0o644); err != nil {
		return err
	}
	classesDir := filepath.Join(buildDir, "classes")
	if err := os.MkdirAll(classesDir, 0o755); err != nil {
		return err
	}
	logf("— javac + d8 (ShireiActivity)")
	if err := runCmd(logf, exec.Command("javac",
		"-classpath", androidJar, "-source", "8", "-target", "8",
		"-Xlint:-options", "-d", classesDir, javaSrc)); err != nil {
		return fmt.Errorf("javac (JDK installed?): %w", err)
	}
	classFiles, err := filepath.Glob(filepath.Join(classesDir, "dev", "shirei", "host", "*.class"))
	if err != nil || len(classFiles) == 0 {
		return fmt.Errorf("no class files produced by javac")
	}
	dexDir := filepath.Join(buildDir, "dex")
	if err := os.MkdirAll(dexDir, 0o755); err != nil {
		return err
	}
	if err := runCmd(logf, toolCommand(buildToolPath(buildTools, "d8"),
		append([]string{"--lib", androidJar, "--output", dexDir}, classFiles...)...)); err != nil {
		return fmt.Errorf("d8: %w", err)
	}
	dexFile := filepath.Join(dexDir, "classes.dex")

	// --- 4. optional launcher icon → aapt2 compile ---
	var compiledIcon string
	iconPath := resolveIconPath(o.PkgDir, o.IconPath)
	if iconPath != "" {
		logf("— launcher icon %s", iconPath)
		compiledIcon, err = prepareLauncherIcon(buildTools, buildDir, iconPath, logf)
		if err != nil {
			return fmt.Errorf("launcher icon: %w", err)
		}
	}

	// --- 5. capabilities → extra uses-permission ---
	caps, err := collectCapabilities(o.PkgDir, logf)
	if err != nil {
		return fmt.Errorf("capabilities: %w", err)
	}

	// --- 6. manifest + aapt2 link ---
	manifest := filepath.Join(buildDir, "AndroidManifest.xml")
	if caps.Orientation != "" {
		logf("— orientation %s (manifest)", caps.Orientation)
	}
	if err := os.WriteFile(manifest, []byte(manifestXML(appID, label, compiledIcon != "", caps.Android, caps.Orientation)), 0o644); err != nil {
		return err
	}
	baseAPK := filepath.Join(buildDir, "base.apk")
	logf("— aapt2 link")
	linkArgs := []string{
		"link", "-o", baseAPK, "--manifest", manifest, "-I", androidJar,
		"--min-sdk-version", fmt.Sprint(minSdk),
		"--target-sdk-version", fmt.Sprint(targetSdk),
	}
	if compiledIcon != "" {
		linkArgs = append(linkArgs, "-R", compiledIcon)
	}
	if err := runCmd(logf, toolCommand(buildToolPath(buildTools, "aapt2"), linkArgs...)); err != nil {
		return fmt.Errorf("aapt2 link: %w", err)
	}

	// --- 7. inject the native lib + dex into the APK ---
	unsigned := filepath.Join(buildDir, "unsigned.apk")
	if err := addFilesToAPK(baseAPK, unsigned, map[string]string{
		"lib/" + abi + "/lib" + libName + ".so": soPath,
		"classes.dex":                           dexFile,
	}); err != nil {
		return fmt.Errorf("inject lib/dex: %w", err)
	}

	// --- 8. zipalign + sign ---
	aligned := filepath.Join(buildDir, "aligned.apk")
	logf("— zipalign")
	if err := runCmd(logf, toolCommand(buildToolPath(buildTools, "zipalign"),
		"-f", "-p", "4", unsigned, aligned)); err != nil {
		return fmt.Errorf("zipalign: %w", err)
	}
	keystore, err := ensureDebugKeystore(logf)
	if err != nil {
		return err
	}
	finalAPK := filepath.Join(buildDir, appName+".apk")
	logf("— apksigner sign")
	if err := runCmd(logf, toolCommand(buildToolPath(buildTools, "apksigner"), "sign",
		"--ks", keystore, "--ks-pass", "pass:android",
		"--ks-key-alias", "androiddebugkey",
		"--out", finalAPK, aligned)); err != nil {
		return fmt.Errorf("apksigner: %w", err)
	}
	logf("APK: %s", finalAPK)

	if o.BuildOnly {
		return nil
	}

	// --- 9. install + launch ---
	adb, err := findADB(sdk)
	if err != nil {
		return err
	}
	logf("— adb install")
	if err := runCmd(logf, adbCmd(adb, o.Serial, "install", "-r", finalAPK)); err != nil {
		return fmt.Errorf("adb install: %w", err)
	}
	logf("— am start")
	if err := runCmd(logf, adbCmd(adb, o.Serial, "shell", "am", "start", "-W",
		"-n", appID+"/dev.shirei.host.ShireiActivity")); err != nil {
		return fmt.Errorf("am start: %w", err)
	}

	if o.Screencap != "" {
		time.Sleep(time.Duration(o.DelayMs) * time.Millisecond)
		logf("— screencap → %s", o.Screencap)
		out, err := adbCmd(adb, o.Serial, "exec-out", "screencap", "-p").Output()
		if err != nil {
			return fmt.Errorf("screencap: %w", err)
		}
		if err := os.WriteFile(o.Screencap, out, 0o644); err != nil {
			return err
		}
	}
	logf("logs: %s logcat shirei:V threaded_app:V AndroidRuntime:E DEBUG:I '*:S'", adb)
	return nil
}

// screencapNow grabs a device screenshot outside a build (GUI button).
func screencapNow(serial, outPath string) error {
	sdk, err := findSDK()
	if err != nil {
		return err
	}
	adb, err := findADB(sdk)
	if err != nil {
		return err
	}
	out, err := adbCmd(adb, serial, "exec-out", "screencap", "-p").Output()
	if err != nil {
		return fmt.Errorf("screencap: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, out, 0o644)
}

func adbCmd(adb, serial string, args ...string) *exec.Cmd {
	if serial != "" {
		args = append([]string{"-s", serial}, args...)
	}
	return exec.Command(adb, args...)
}

// manifestXML: the activity is ShireiActivity (NativeActivity subclass in
// classes.dex) so soft-keyboard/IME input works; adjustResize turns keyboard
// show/hide into a window resize, which the backend reads per frame.
// extraPerms come from shirei.capabilities on the app's Go module deps.
func manifestXML(appID, label string, withIcon bool, extraPerms []string, orientation string) string {
	iconAttr := ""
	if withIcon {
		iconAttr = ` android:icon="@mipmap/ic_launcher"`
	}
	extra := androidPermissionXML(extraPerms)
	// Package visibility (API 30+): declare intents we start so the system
	// can resolve them. Camera capture is required when the camera capability
	// is present (otherwise resolveActivity / chooser behavior breaks).
	queriesExtra := ""
	for _, p := range extraPerms {
		if p == "android.permission.CAMERA" {
			queriesExtra = `
    <intent>
      <action android:name="android.media.action.IMAGE_CAPTURE"/>
    </intent>`
			break
		}
	}
	// screenOrientation from orientation-landscape / orientation-portrait tokens.
	// Empty = system default (sensor / unspecified).
	orientAttr := ""
	switch orientation {
	case "landscape":
		orientAttr = ` android:screenOrientation="sensorLandscape"`
	case "portrait":
		orientAttr = ` android:screenOrientation="sensorPortrait"`
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package=%q>
  <uses-permission android:name="android.permission.INTERNET"/>
%s  <!-- Package visibility (API 30+): browser VIEW + capability-driven intents. -->
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
    </intent>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="http"/>
    </intent>%s
  </queries>
  <application android:label=%q%s android:debuggable="true"
      android:theme="@android:style/Theme.Material.NoActionBar">
    <activity android:name="dev.shirei.host.ShireiActivity" android:exported="true"
        android:windowSoftInputMode="adjustResize"%s
        android:configChanges="orientation|screenSize|screenLayout|smallestScreenSize|keyboard|keyboardHidden|uiMode|density|locale|fontScale">
      <meta-data android:name="android.app.lib_name" android:value=%q/>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
  </application>
</manifest>
`, appID, extra, queriesExtra, label, iconAttr, orientAttr, libName)
}

// prepareLauncherIcon resizes src to xxxhdpi and aapt2-compiles it to a .flat
// for aapt2 link -R. Returns the path to the compiled flat file.
func prepareLauncherIcon(buildTools, buildDir, src string, logf logFn) (string, error) {
	f, err := os.Open(src)
	if err != nil {
		return "", err
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		return "", fmt.Errorf("decode: %w", err)
	}
	dst := image.NewRGBA(image.Rect(0, 0, launcherIconSize, launcherIconSize))
	draw.CatmullRom.Scale(dst, dst.Bounds(), img, img.Bounds(), draw.Over, nil)

	resDir := filepath.Join(buildDir, "res", "mipmap-xxxhdpi")
	if err := os.MkdirAll(resDir, 0o755); err != nil {
		return "", err
	}
	pngPath := filepath.Join(resDir, "ic_launcher.png")
	out, err := os.Create(pngPath)
	if err != nil {
		return "", err
	}
	if err := png.Encode(out, dst); err != nil {
		out.Close()
		return "", err
	}
	if err := out.Close(); err != nil {
		return "", err
	}

	compiledDir := filepath.Join(buildDir, "compiled")
	if err := os.MkdirAll(compiledDir, 0o755); err != nil {
		return "", err
	}
	// aapt2 compile writes <dir>_<name>.flat into -o directory when -o is a dir.
	if err := runCmd(logf, toolCommand(buildToolPath(buildTools, "aapt2"),
		"compile", "-o", compiledDir+string(filepath.Separator), pngPath)); err != nil {
		return "", fmt.Errorf("aapt2 compile: %w", err)
	}
	// Find the produced .flat (name varies slightly by aapt2 version).
	flats, err := filepath.Glob(filepath.Join(compiledDir, "*.flat"))
	if err != nil || len(flats) == 0 {
		return "", fmt.Errorf("aapt2 compile produced no .flat in %s", compiledDir)
	}
	return flats[0], nil
}

// addFilesToAPK rewrites src as dst with extra (deflated) entries. aapt2's
// own entries are copied raw so resources.arsc stays stored/aligned.
func addFilesToAPK(srcAPK, dstAPK string, entries map[string]string) error {
	zr, err := zip.OpenReader(srcAPK)
	if err != nil {
		return err
	}
	defer zr.Close()
	out, err := os.Create(dstAPK)
	if err != nil {
		return err
	}
	defer out.Close()
	zw := zip.NewWriter(out)
	for _, f := range zr.File {
		raw, err := f.OpenRaw()
		if err != nil {
			return err
		}
		hdr := f.FileHeader
		w, err := zw.CreateRaw(&hdr)
		if err != nil {
			return err
		}
		if _, err := io.Copy(w, raw); err != nil {
			return err
		}
	}
	for entryName, filePath := range entries {
		src, err := os.Open(filePath)
		if err != nil {
			return err
		}
		w, err := zw.Create(entryName)
		if err != nil {
			src.Close()
			return err
		}
		_, err = io.Copy(w, src)
		src.Close()
		if err != nil {
			return err
		}
	}
	return zw.Close()
}

func ensureDebugKeystore(logf logFn) (string, error) {
	dir, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	ks := filepath.Join(dir, ".android", "debug.keystore")
	if _, err := os.Stat(ks); err == nil {
		return ks, nil
	}
	if err := os.MkdirAll(filepath.Dir(ks), 0o755); err != nil {
		return "", err
	}
	logf("— generating debug keystore %s", ks)
	if err := runCmd(logf, exec.Command("keytool", "-genkeypair",
		"-keystore", ks, "-storepass", "android",
		"-alias", "androiddebugkey", "-keypass", "android",
		"-keyalg", "RSA", "-keysize", "2048", "-validity", "10000",
		"-dname", "CN=Android Debug,O=Android,C=US")); err != nil {
		return "", fmt.Errorf("keytool: %w", err)
	}
	return ks, nil
}

// ndkHostTag is the NDK's name for the host toolchain directory. The darwin
// prebuilts are universal binaries, so x86_64 is correct on Apple Silicon too.
// Linux ships only linux-x86_64 host tools — there is no official linux-aarch64
// NDK (Google); arm64 Linux hosts cannot run that prebuilt (Exec format error).
func ndkHostTag() string {
	switch runtime.GOOS {
	case "darwin":
		return "darwin-x86_64"
	case "windows":
		return "windows-x86_64"
	default:
		return "linux-x86_64"
	}
}

// checkNDKHostToolchain verifies the NDK clang wrapper exists and fails early
// with a clear message on unsupported host architectures (notably Linux arm64).
func checkNDKHostToolchain(ndk, cc string) error {
	if _, err := os.Stat(cc); err != nil {
		return fmt.Errorf("NDK clang not found: %s", cc)
	}
	// Official Linux NDK is x86_64-only. On arm64 Linux the wrapper exists but
	// the real clang is an x86_64 ELF → "cannot execute binary file".
	if runtime.GOOS == "linux" && runtime.GOARCH == "arm64" {
		return fmt.Errorf("Android NDK host tools are x86_64-only; this Linux is arm64 (aarch64).\n"+
			"  Google does not ship a linux-aarch64 NDK, so mobilerun cannot build here.\n"+
			"  Use a x86_64 Linux host/VM, or run on macOS (Apple Silicon is fine).\n"+
			"  See docs/android.md § Linux. NDK path: %s", ndk)
	}
	return nil
}

// buildToolPath resolves a build-tools executable, accounting for Windows
// shipping some of them (apksigner, d8, sdkmanager) as .bat scripts.
func buildToolPath(buildTools, name string) string {
	p := filepath.Join(buildTools, name)
	if runtime.GOOS != "windows" {
		return p
	}
	for _, ext := range []string{".exe", ".bat", ".cmd"} {
		if _, err := os.Stat(p + ext); err == nil {
			return p + ext
		}
	}
	return p
}

func findSDK() (string, error) {
	candidates := []string{
		os.Getenv("ANDROID_HOME"),
		os.Getenv("ANDROID_SDK_ROOT"),
	}
	home, _ := os.UserHomeDir()
	switch runtime.GOOS {
	case "darwin":
		candidates = append(candidates,
			"/opt/homebrew/share/android-commandlinetools",
			filepath.Join(home, "Library/Android/sdk"))
	case "windows":
		if lad := os.Getenv("LOCALAPPDATA"); lad != "" {
			candidates = append(candidates, filepath.Join(lad, "Android", "Sdk"))
		}
	default: // linux and friends
		candidates = append(candidates,
			filepath.Join(home, "Android/Sdk"),
			"/usr/lib/android-sdk")
	}
	for _, c := range candidates {
		if c == "" {
			continue
		}
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("Android SDK not found (set ANDROID_HOME)")
}

func findADB(sdk string) (string, error) {
	if p, err := exec.LookPath("adb"); err == nil {
		return p, nil
	}
	p := filepath.Join(sdk, "platform-tools", "adb")
	if runtime.GOOS == "windows" {
		p += ".exe"
	}
	if _, err := os.Stat(p); err == nil {
		return p, nil
	}
	return "", fmt.Errorf("adb not found")
}

// newestSubdir returns the lexically greatest entry — SDK component dirs are
// version-named so this picks the newest install.
func newestSubdir(parent string) (string, error) {
	ents, err := os.ReadDir(parent)
	if err != nil {
		return "", err
	}
	var names []string
	for _, e := range ents {
		if e.IsDir() {
			names = append(names, e.Name())
		}
	}
	if len(names) == 0 {
		return "", fmt.Errorf("no entries in %s", parent)
	}
	sort.Strings(names)
	return filepath.Join(parent, names[len(names)-1]), nil
}

func findUp(dir, name string) string {
	for {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func sanitizeName(s string) string {
	s = nonAlnum.ReplaceAllString(strings.ToLower(s), "")
	if s == "" || s[0] >= '0' && s[0] <= '9' {
		s = "a" + s
	}
	return s
}

// androidPackageName builds a valid Android application id (manifest package).
// Rules enforced by aapt2: at least two dot-separated segments; each segment
// [a-z][a-z0-9_]* — no hyphens. Empty id → {prefix}.{sanitized-folder}.
// A user-supplied id is cleaned segment-by-segment; if it has no dots after
// cleaning, the prefix is prepended (so "hacker-news-reader" becomes
// "dev.shirei.hackernewsreader", not a single invalid segment).
func androidPackageName(id, prefix, folderBase string) string {
	prefix = strings.TrimSpace(prefix)
	if prefix == "" {
		prefix = defaultAppIDPrefix
	}
	prefix = strings.TrimRight(prefix, ".")
	// Sanitize prefix segments too (user may type "dev.hasen" or "dev-hasen").
	prefix = joinAndroidSegments(splitAndSanitizeAndroidSegments(prefix))
	if prefix == "" {
		prefix = defaultAppIDPrefix
	}

	id = strings.TrimSpace(id)
	if id == "" {
		return prefix + "." + sanitizeName(folderBase)
	}

	segs := splitAndSanitizeAndroidSegments(id)
	if len(segs) == 0 {
		return prefix + "." + sanitizeName(folderBase)
	}
	// Single segment (e.g. "hacker-news-reader" → "hackernewsreader") needs a prefix.
	if len(segs) == 1 {
		return prefix + "." + segs[0]
	}
	return strings.Join(segs, ".")
}

func splitAndSanitizeAndroidSegments(s string) []string {
	// Allow both dots and hyphens as separators so "hacker-news" becomes one
	// sanitized segment if used as a whole id, and "dev.hasen.hn" keeps dots.
	// Hyphens *inside* a segment are stripped by sanitizeName; hyphens used
	// as only separator without dots collapse into one segment — which is
	// correct: "hacker-news-reader" is not reverse-DNS.
	parts := strings.Split(s, ".")
	var out []string
	for _, p := range parts {
		p = sanitizeName(p) // strips hyphens/spaces to [a-z0-9]+
		if p == "" {
			continue
		}
		out = append(out, p)
	}
	return out
}

func joinAndroidSegments(segs []string) string {
	if len(segs) == 0 {
		return ""
	}
	return strings.Join(segs, ".")
}

// toolCommand builds an *exec.Cmd for an SDK/build-tools executable.
// On Windows, .bat/.cmd wrappers must go through cmd.exe — CreateProcess
// cannot run them directly.
func toolCommand(name string, args ...string) *exec.Cmd {
	if runtime.GOOS == "windows" {
		switch strings.ToLower(filepath.Ext(name)) {
		case ".bat", ".cmd":
			// /c <bat> <args...>; quote path if needed via Cmd.Args handling.
			full := append([]string{"/c", name}, args...)
			return exec.Command("cmd", full...)
		}
	}
	return exec.Command(name, args...)
}

// runCmd streams a subprocess's stdout+stderr through logf, line by line.
func runCmd(logf logFn, cmd *exec.Cmd) error {
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}
	var wg sync.WaitGroup
	pump := func(rd io.Reader) {
		defer wg.Done()
		sc := bufio.NewScanner(rd)
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		for sc.Scan() {
			logf("%s", sc.Text())
		}
	}
	wg.Add(2)
	go pump(stdout)
	go pump(stderr)
	wg.Wait()
	return cmd.Wait()
}
